### ISSUE TITLE
Incompatible .framework file. 

### ISSUE THREAD

**Issue by Shoshin23** [colbylwilliams/CustomVision#1]
Hi, 

I'm using  Xcode 9.4, the latest stable release. I was trying to setup your framework but got the following error:
"Incompatible Swift version - framework was built with 4.1 (swiftlang-902.0.48 clang-902.0.37.1) and the local version is 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2).

How do I fix this? 

Thanks!

Also, would greatly appreciate a Pod for this project. Very useful to my requirements. :)

**Comment by colbylwilliams** [comment]
@Shoshin23 just rebuilt with latest Xcode and published a new release (v0.3.4).  should fix your issue, please let me know.

**Comment by Shoshin23** [comment]
Hi @colbylwilliams I dont get this error anymore. 

I have one more question. Can you outline the broad steps to use the SDK? I'm trying to following:

in AppDelegate.swift
CustomVisionClient.shared.trainingKey   = "58cd2b2c9fd043eca6f234d70b10f20d"
CustomVisionClient.shared.predictionKey = "bf8b509b39fc43efa5cb1781483e6961"

in my training file
import CustomVision

        let tag = "Airpods"     // doesn't exist in project yet
        let images: [UIImage] = [image array]
        
        client.createImages(from: images, withNewTagNamed: tag) { r in
            print(r.resource) //I get nil here. 
        } 

I don't really know how to proceed next. Any help with this would be great. :)

**Comment by colbylwilliams** [comment]
I’ll update the docs.  In the meantime, see this project: https://github.com/colbylwilliams/RetailVision
